<a href="https://colab.research.google.com/github/sharad272/PyTorch/blob/main/NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape


(569, 33)

In [ ]:
df.drop(columns=['Unnamed: 32','id'],inplace=True)

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## train-test

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

## Scaling


In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[ 1.79243606,  0.35660069,  1.75430694, ...,  0.74549954,
         0.51453507, -1.08286708],
       [ 0.45853455,  0.25490484,  0.4376782 , ...,  0.53868599,
         1.75889465,  1.30857496],
       [ 1.10287681, -0.56834732,  1.04882363, ...,  0.62511553,
        -0.09396159, -0.04904904],
       ...,
       [ 1.71048025,  0.08299042,  1.71739212, ...,  1.60979495,
         0.21189652, -0.13337352],
       [-0.78210691, -0.39401157, -0.79732776, ..., -0.40154395,
         0.11691953, -0.31888736],
       [ 1.68504569,  1.12900493,  1.75430694, ...,  1.22394878,
         0.63365876,  0.65028191]])

 import torch

X = torch.tensor([[10.0, 20.0],
                  [30.0, 40.0],
                  [50.0, 60.0]])

# FIT
mean = X.mean(dim=0)
std = X.std(dim=0)

# TRANSFORM
X_scaled = (X - mean) / std


## Label Encoder to convert Y_Train into encoding to make NN understandable

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,

In [ ]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
X_train_tensor

tensor([[ 1.7924,  0.3566,  1.7543,  ...,  0.7455,  0.5145, -1.0829],
        [ 0.4585,  0.2549,  0.4377,  ...,  0.5387,  1.7589,  1.3086],
        [ 1.1029, -0.5683,  1.0488,  ...,  0.6251, -0.0940, -0.0490],
        ...,
        [ 1.7105,  0.0830,  1.7174,  ...,  1.6098,  0.2119, -0.1334],
        [-0.7821, -0.3940, -0.7973,  ..., -0.4015,  0.1169, -0.3189],
        [ 1.6850,  1.1290,  1.7543,  ...,  1.2239,  0.6337,  0.6503]])

## Defining the Model


In [ ]:
class MySimpleNN():
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1, dtype = torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype = torch.float64,requires_grad=True)

  def forward(self,x):
    z = torch.matmul(x.float(),self.weights.float()) + self.bias.float()
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss







## Learning Rate

In [ ]:
learning_rate = 0.1
epochs = 25

Training the Model

In [ ]:
model = MySimpleNN(X_train_tensor)
# define loop
for epoch in range(epochs):

   #Forward Pass
   y_pred = model.forward(X_train_tensor)
   #print(y_pred)

  #Loss Calculation
   loss = model.loss_function(y_pred,y_train_tensor)
   print(loss)

  #Backward Pass (To calculate derivatives)
   loss.backward()

  #Update Gradients
  #Parameters update
   with torch.no_grad(): #Don't track the gradients while updating it
      model.weights -= learning_rate * model.weights.grad
      model.bias -= learning_rate * model.bias.grad

  #Zero gradients (To keep the gradient for each epoch)
      model.weights.grad.zero_()
      model.bias.grad.zero_()

      print(f"Echo: {epoch +1}, Loss`: {loss}")



tensor(3.9397, dtype=torch.float64, grad_fn=<NegBackward0>)
Echo: 1, Loss`: 3.939729091834603
tensor(3.8338, dtype=torch.float64, grad_fn=<NegBackward0>)
Echo: 2, Loss`: 3.833811306973522
tensor(3.7202, dtype=torch.float64, grad_fn=<NegBackward0>)
Echo: 3, Loss`: 3.7202054455372147
tensor(3.6033, dtype=torch.float64, grad_fn=<NegBackward0>)
Echo: 4, Loss`: 3.603276012641918
tensor(3.4816, dtype=torch.float64, grad_fn=<NegBackward0>)
Echo: 5, Loss`: 3.4816405735917937
tensor(3.3542, dtype=torch.float64, grad_fn=<NegBackward0>)
Echo: 6, Loss`: 3.354218012225442
tensor(3.2254, dtype=torch.float64, grad_fn=<NegBackward0>)
Echo: 7, Loss`: 3.2254103593288743
tensor(3.0918, dtype=torch.float64, grad_fn=<NegBackward0>)
Echo: 8, Loss`: 3.091766580935289
tensor(2.9544, dtype=torch.float64, grad_fn=<NegBackward0>)
Echo: 9, Loss`: 2.9543911082318233
tensor(2.8134, dtype=torch.float64, grad_fn=<NegBackward0>)
Echo: 10, Loss`: 2.81337445643528
tensor(2.6673, dtype=torch.float64, grad_fn=<NegBackward

In [ ]:
model.bias

tensor([-0.1296], dtype=torch.float64, requires_grad=True)

In [ ]:
model.weights

tensor([[-0.3719],
        [ 0.5292],
        [ 0.2201],
        [-0.1092],
        [-0.0998],
        [ 0.2268],
        [-0.4138],
        [-0.3103],
        [ 0.3577],
        [ 0.2107],
        [-0.1727],
        [ 0.3669],
        [ 0.0998],
        [ 0.1121],
        [ 0.1914],
        [ 0.1856],
        [ 0.2108],
        [-0.2640],
        [ 0.5004],
        [-0.2688],
        [-0.2815],
        [ 0.2148],
        [ 0.2328],
        [ 0.3283],
        [ 0.3669],
        [ 0.3451],
        [ 0.2882],
        [-0.1246],
        [ 0.2908],
        [ 0.0403]], dtype=torch.float64, requires_grad=True)

## Model Evaluation

In [ ]:
with torch.no_grad() :
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()   # Thresholding step
  accuracy = (y_pred == y_test_tensor).float().mean() # Accuracy = correctness_predictions / Total Predictions
  print(f'Accuracy: {accuracy.item()*100}')


Accuracy: 56.9252073764801


## Using Mini Batch Grad method i.e. to the batches of data


In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self, index):

    return self.features[index], self.labels[index]

In [ ]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)  # Load the data from DataSet class
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [ ]:
train_dataset[0]

(tensor([-0.5995, -1.9489, -0.6292, -0.5888, -0.5254, -0.9894, -0.7734, -0.7935,
         -0.7317, -1.0222, -0.5856, -0.3067, -0.6463, -0.4889, -0.2931, -0.7529,
         -0.5627, -0.9671, -1.1416, -0.7106, -0.4879, -0.8959, -0.5614, -0.4938,
          0.2335, -0.5930, -0.5436, -0.6715, -0.6905, -0.6130],
        dtype=torch.float64),
 tensor(0))

In [ ]:
# To make the batches of the above data
train_dataload = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_dataload = DataLoader(test_dataset,batch_size= 32, shuffle= True)


## Defining the Model

In [ ]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])
print(model.parameters)
model.forward(X_train_tensor)

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

<bound method Module.parameters of MySimpleNN(
  (linear): Linear(in_features=30, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)>


In [ ]:
# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_dataload:
    batch_features = batch_features.float()
    batch_labels = batch_labels.float()
    # forward pass
    y_pred = model.forward(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.31485122442245483
Epoch: 2, Loss: 0.10977882891893387
Epoch: 3, Loss: 0.17125041782855988
Epoch: 4, Loss: 0.12212290614843369
Epoch: 5, Loss: 0.050366610288619995
Epoch: 6, Loss: 0.09346580505371094
Epoch: 7, Loss: 0.095231793820858
Epoch: 8, Loss: 0.09805800020694733
Epoch: 9, Loss: 0.013206777162849903
Epoch: 10, Loss: 0.03188662230968475
Epoch: 11, Loss: 0.06742389500141144
Epoch: 12, Loss: 0.014411330223083496
Epoch: 13, Loss: 0.37206342816352844
Epoch: 14, Loss: 0.06802881509065628
Epoch: 15, Loss: 0.03915203735232353
Epoch: 16, Loss: 0.06774631887674332
Epoch: 17, Loss: 0.042931970208883286
Epoch: 18, Loss: 0.0325658842921257
Epoch: 19, Loss: 0.2502777874469757
Epoch: 20, Loss: 0.19902272522449493
Epoch: 21, Loss: 0.06274046748876572
Epoch: 22, Loss: 0.04392167925834656
Epoch: 23, Loss: 0.008067389950156212
Epoch: 24, Loss: 0.009207458235323429
Epoch: 25, Loss: 0.3653676211833954


In [ ]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_dataload:
        batch_features = batch_features.float()
        batch_labels = batch_labels.float()
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9609
