<a href="https://colab.research.google.com/github/sharad272/PyTorch/blob/main/NN_optim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
class Model(nn.Module):
  def __init__(self, num_features) -> None:
    super().__init__()   # calling the constructor of nn.Module class to use nn.Linear & nn.Sigmoid

    # Create Layer
    self.linear = nn.Linear(num_features, 1) #nn.Linear(input,output)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)  #Linear Transformation
    out = self.sigmoid(out)      #Activation Function
    return out




In [ ]:
#create  dataset
features = torch.rand(10,5)  # rows = 10 & cols = 5

#create model

model = Model(features.shape[1])  # take the cols as an arguemnt


# call Model fo forward pass
#model = model.forward(features)

# Due to magic function __call__ by default if you call an object of the class, NN class would call forward function

model(features)


tensor([[0.3979],
        [0.4043],
        [0.3565],
        [0.3536],
        [0.4024],
        [0.3610],
        [0.4214],
        [0.4448],
        [0.4352],
        [0.4359]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight   # to see the weights

Parameter containing:
tensor([[-0.4291,  0.3681, -0.1978,  0.3130, -0.1085]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.4048], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model)


Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            6
├─Sigmoid: 1-2                           --
Total params: 6
Trainable params: 6
Non-trainable params: 0

In [ ]:
# 6 is 5 weights and 1 bias

## NN using hidden layer


In [ ]:
class Model(nn.Module):
  def __init__(self, num_features) -> None:
    super().__init__()   # calling the constructor of nn.Module class to use nn.Linear & nn.Sigmoid

    # Create Layers
    self.linear1 = nn.Linear(num_features, 3) #nn.Linear(input,output)
    self.relu = nn.ReLU()  # For hidden layer/s activation function is RELU
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear1(features)  #Linear Layer 1 Transformation
    out = self.relu(out)          #Activation Function for hidden layer
    out = self.linear2(out)      #Linear Layer 2 Transformation
    out = self.sigmoid(out)      #Activation Function
    return out




In [ ]:
#create  dataset
features = torch.rand(10,5)  # rows = 10 & cols = 5

#create model

model = Model(features.shape[1])  # take the cols as an arguemnt


# call Model fo forward pass
#model = model.forward(features)

# Due to magic function __call__ by default if you call an object of the class, NN class would call forward function

model(features)

tensor([[0.5314],
        [0.5104],
        [0.5337],
        [0.5135],
        [0.5128],
        [0.5222],
        [0.5148],
        [0.5017],
        [0.5144],
        [0.5153]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight


Parameter containing:
tensor([[ 0.3714, -0.2127, -0.2838,  0.3402, -0.2335],
        [ 0.3273, -0.4383,  0.1379, -0.4327,  0.0816],
        [-0.4106, -0.4361,  0.0064,  0.0871,  0.3887]], requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[-0.0735,  0.3990, -0.1852]], requires_grad=True)

In [ ]:
model.linear1.bias

Parameter containing:
tensor([ 0.4191,  0.0767, -0.1072], requires_grad=True)

In [ ]:
model.linear2.bias

Parameter containing:
tensor([0.0616], requires_grad=True)

In [ ]:
summary(model)

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            18
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 22
Trainable params: 22
Non-trainable params: 0

## NN using Sequential Container

In [ ]:

import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()

    )

  def forward(self, features):

    out = self.network(features)

    return out

In [ ]:
# For Loss funtion
loss = nn.BCELoss(y_pred,y)  # BCE is the binary cross entropy loss function
loss

NameError: name 'y_pred' is not defined

In [ ]:
# define optmizer after creating the model (It skipped the parameter update logic)

optmimizer = torch.optim.Adam(model.parameters(), lr=0.01)  # lr is learning rate
                                                            # model.parameters() is an iterable over trainable parameters (Weights & biases)
optmimizer
optmimizer.zero_grad()  # It should be done before backward pass

#loss.backward()


# To update the Parameters (weights & biases)

optmimizer.step()