<a href="https://colab.research.google.com/github/sharad272/PyTorch/blob/main/pytorch_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def dy_dx(x):
  return 2*x

In [ ]:
dy_dx(3)

6

In [ ]:
import math
def dz_dx(x):
 return 2*x*math.cos(x**2)

In [ ]:
dz_dx(3)

-5.466781571308061

## Using Autograd

In [ ]:
import torch

In [ ]:
x= torch.tensor(3.0,requires_grad=True) # Requires grad means pytorch keeps track in order to compute the differentiation

In [ ]:
x

tensor(3., requires_grad=True)

In [ ]:
y=x**2
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
## PyTorch makes the Computation graph for the above
# Like this   x--sqrt--y
# That's why it knows grad_fn=<PowBackward0> for y

In [ ]:
y.backward()


In [ ]:
x.grad  # To calculate the differentiation

tensor(6.)

In [ ]:
a=torch.tensor(4.0,requires_grad=True)
a

tensor(4., requires_grad=True)

In [ ]:
b=a**2
b

tensor(16., grad_fn=<PowBackward0>)

In [ ]:
c=torch.sin(b)
c

tensor(-0.2879, grad_fn=<SinBackward0>)

In [ ]:
## Computation Graph created by the above

# x--> sqrt --> y --> sin --> c

In [ ]:
c.backward()   # To calculate the  derivative

In [ ]:
a.grad

tensor(-7.6613)

In [ ]:
import torch
x=torch.tensor(6.7)
y=torch.tensor(0.0)
w= torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [ ]:
w

tensor(1., requires_grad=True)

In [ ]:
b

tensor(0., requires_grad=True)

In [ ]:
#Forward Pass
z=w*x+b         # Linear Transformation
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [ ]:
y_pred = torch.sigmoid(z)  # Activation function
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [ ]:
import torch.nn.functional as F

# Loss function
loss = F.binary_cross_entropy(y_pred, y)
loss

tensor(6.7012, grad_fn=<BinaryCrossEntropyBackward0>)

In [ ]:
loss.backward()

In [ ]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


In [ ]:
x = torch.tensor([1.0,2.0,3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [ ]:
y=(x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [ ]:
y.backward()


In [ ]:
x.grad   # getting 3 gradients one for each input of x

tensor([0.6667, 1.3333, 2.0000])

In [ ]:
# clearing grad
x.grad.zero_()

tensor([0., 0., 0.])

## Keep the grad tracking off

In [ ]:
#option 1: required_grad_(False)
#option 2: detach()
#option 3: torch.nograd()

In [ ]:
x.requires_grad_(False)
x

tensor([1., 2., 3.])

In [ ]:
y = x**2
y

tensor([1., 4., 9.])

In [ ]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
x = torch.tensor(1.0,requires_grad= True)
x

tensor(1., requires_grad=True)

In [ ]:
y = x**2
y

tensor(1., grad_fn=<PowBackward0>)

In [ ]:
z = x.detach()
z

tensor(1.)

In [ ]:
y1 = z**2
y1

tensor(1.)