<a href="https://colab.research.google.com/github/sharad272/PyTorch/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Colab!

In [ ]:
import torch

In [ ]:
if torch.cuda.is_available():
    device = torch.cuda.get_device_name(0)
else:
    device = torch.device("cpu")
print(device)

Tesla T4


## Creating a Tensor

In [ ]:
# Using empty()
torch.empty(2,3)

tensor([[5.2872e-08, 0.0000e+00, 1.5596e-42],
        [0.0000e+00, 5.2872e-08, 0.0000e+00]])

In [ ]:
a= torch.empty(2,3)
print(type(a))

<class 'torch.Tensor'>


In [ ]:
## Using zeroes
print(torch.zeros(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
## Using ones
print(torch.ones(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
## Using rand
print(torch.rand(2,3))

tensor([[0.1651, 0.0515, 0.2419],
        [0.1804, 0.7915, 0.3441]])


In [ ]:
## Using seed
torch.manual_seed(42)   #It fixed the values
print(torch.rand(2,3))

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [ ]:
## Using tensor
print(torch.tensor([[1,2,3],[4,5,6]]))

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
##Using arange
print(torch.arange(0,10))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## Shape of Tensor


In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
print(torch.empty_like(x))   ## Copy the same tensor but with x-like config

tensor([[493921239150, 489626271855, 390842023976],
        [210453397595, 214748364844, 219043332140]])


In [ ]:
print(torch.ones_like(x))

tensor([[1, 1, 1],
        [1, 1, 1]])


In [ ]:
print(torch.rand_like(float(x)))

ValueError: only one element tensors can be converted to Python scalars

## Tensor Data Type


In [ ]:
x.dtype

torch.int64

In [ ]:
## assign data type
print(torch.tensor([[1.0,2.3,3.1],[4.3,5.4,6.3]] , dtype= torch.int32 ))

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


## Change to CUDA I.E. GPU


In [ ]:
device = torch.device('cuda')
print(device)

cuda


In [ ]:
x.to(device=device)           ## Copy the tensor array to CUDA

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

## Convert Tensor to Numpy


In [ ]:
y=x.numpy()             #Conver tensor type into numpy
y

NameError: name 'x' is not defined